---
title: "Workflow: L0"
author: "COMPASS workflows team"
title-block-banner: true
params:
  html_outfile: "L0.html"
  raw: "Raw/"
  raw_done: "Raw_done/"
  L0: "L0/"
  logfile: ""
date: now
date-format: "YYYY-MM-DD HH:mm:ssZ"
format: 
  html:
    code-fold: true
editor: visual
---

## Initializing

```{r}
library(compasstools)
if(!exists("read_datalogger_file")) {
    stop("Please update to latest version of compasstools!\n",
         "devtools::install_github('COMPASS-DOE/compasstools')")
}
library(readr)
files_to_process <- list.files(params$raw, pattern = "*.dat$", full.names = TRUE, recursive = TRUE)

source("helpers.R")
```

I see `r length(files_to_process)` files to process.

Writing to `r normalizePath(params$L0)`.

HTML outfile is `r params$html_outfile`.

Logfile is `r params$logfile`.

Working directory is `r getwd()`.

## Processing

```{r}
file_overwrites <- 0
errors_occurred <- 0

f <- function(fn, new_dir) {
    message(Sys.time(), " Processing ", basename(fn))
    dat <- try(compasstools::read_datalogger_file(fn))
    new_fn <- gsub("\\.dat$", "_L0\\.csv", basename(fn))
    note <- ""
    if(is.data.frame(dat)) {
        message("\tWriting ", new_fn)
        if(file.exists(file.path(new_dir, new_fn))) {
            note <- "Overwriting existing file!"
            file_overwrites <<- file_overwrites + 1
        }
        err <- try(write.csv(dat, file.path(new_dir, new_fn), row.names = FALSE))
        if(is.null(err)) {
            # Move to 'Raw_done' folder
            #file.copy(fn, file.path(params$raw_done, basename(fn)), overwrite = FALSE) # TODO
            #file.remove(fn)  # TODO
        } else {
            note <- "Write error"
            errors_occurred <<- errors_occurred + 1
        }
    } else {
        note <- "Read error"
        errors_occurred <<- errors_occurred + 1
    }
    data.frame(File = basename(fn),
               Logger = dat$Logger[1],
               Table = dat$Table[1],
               Rows = nrow(dat),
               Columns = ncol(dat),
               Note = note)
}

out <- lapply(files_to_process, f, new_dir = params$L0)
```

## Summary

```{r}
#| echo: false
#| output: asis
if(file_overwrites) {
    cat("### WARNING: ", file_overwrites, " file overwrite(s)\n")
    log_warning(paste("File overwrite(s)", params$html_outfile), 
                logfile = params$logfile)
}
if(errors_occurred) {
    cat("### WARNING: ", errors_occurred, " file read/write error(s)\n")
    log_warning(paste("File read/write error(s)", params$html_outfile), 
                logfile = params$logfile)
}
```

```{r}
out_df <- do.call("rbind", out)
knitr::kable(out_df)
```

## Reproducibility

```{r}
sessionInfo()
```
